version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "weekly"
