package de.tum.cit.aet.thesis.thesis.constants;

/**
 * Tracks who authored a feedback item.
 * <ul>
 *   <li>{@link #AI} — item was generated by the AI review pipeline and saved as-is.</li>
 *   <li>{@link #HUMAN} — an instructor typed the item manually.</li>
 *   <li>{@link #AI_REVIEWED_BY_HUMAN} — an AI finding that an instructor edited or accepted
 *   through the preview flow, marking it as human-approved.</li>
 * </ul>
 */
public enum ThesisFeedbackSource {
	AI,
	HUMAN,
	AI_REVIEWED_BY_HUMAN
}
