spring:
  liquibase:
    contexts: dev
  mail:
    host: localhost
    port: 1125
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          starttls:
            enable: false
            required: false

thesis-management:
  mail:
    enabled: true
