-- ============================================================================
-- Conditional insert/update script to complement example users in the database.
--
-- This script:
--   - Inserts six example users with diverse study programs, genders, and nationalities,
--   - Ensures compatibility with Keycloak-managed users: existing values (e.g. name, email, user_id)
--     are preserved and only fields not set by Keycloak are added,
--   - Uses ON CONFLICT logic to avoid overwriting Keycloak-populated fields.
--
-- IMPORTANT:
-- This script is NOT part of the standard Liquibase migration process,
-- and must only be used for local development or manual test environments.
-- These users do NOT exist on the production server and must NEVER be inserted there.
--
-- Author: Marc Fett
-- Date: 2025/05/06
-- ============================================================================

INSERT INTO users (user_id,
                   university_id,
                   matriculation_number,
                   email,
                   first_name,
                   last_name,
                   gender,
                   nationality,
                   cv_filename,
                   degree_filename,
                   examination_filename,
                   study_degree,
                   study_program,
                   projects,
                   interests,
                   special_skills,
                   enrolled_at,
                   updated_at,
                   joined_at,
                   custom_data,
                   avatar,
                   research_group_id)
VALUES (gen_random_uuid(),
        'sam_fischer',
        06000001,
        'sam_fischer@gmail.com',
        'Sam',
        'Fischer',
        'MALE',
        'DE',
        NULL,
        NULL,
        NULL,
        'MASTER',
        'COMPUTER_SCIENCE',
        'AI-based tutor recommendation system',
        'Educational technology, backend development',
        'Java, Spring Boot, PostgreSQL',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'jane_doe',
        06000002,
        'jane_doe@gmail.com',
        'Jane',
        'Doe',
        'FEMALE',
        'US',
        NULL,
        NULL,
        NULL,
        'BACHELOR',
        'INFORMATION_SYSTEMS',
        NULL,
        'Process optimization, business analytics',
        NULL,
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'joey_read',
        06000003,
        'joey_read@gmail.com',
        'Joey',
        'Read',
        'OTHER',
        'CA',
        NULL,
        NULL,
        NULL,
        'MASTER',
        'GAMES_ENGINEERING',
        'Streaming pipeline for sensor data',
        'Real-time systems, cloud platforms',
        'Python, Kafka, AWS',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'barney_young',
        NULL,
        'barney_young@gmail.com',
        'Barney',
        'Young',
        'MALE',
        'DE',
        NULL,
        NULL,
        NULL,
        'BACHELOR',
        'MANAGEMENT_AND_TECHNOLOGY',
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'chloe_mitchell',
        06000005,
        'chloe_mitchell@gmail.com',
        'Chloe',
        'Mitchell',
        'FEMALE',
        'FR',
        NULL,
        NULL,
        NULL,
        'MASTER',
        'OTHER',
        'Usability study for academic tools',
        'Interface design, eye-tracking',
        'Figma, UX research',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'kelly_wilkins',
        NULL,
        'kelly_wilkins@gmail.com',
        'Kelly',
        'Wilkins',
        'FEMALE',
        'UK',
        NULL,
        NULL,
        NULL,
        'BACHELOR',
        'OTHER',
        NULL,
        'Web design, media production',
        'Adobe Suite, HTML/CSS',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL)
ON CONFLICT (university_id) DO UPDATE SET matriculation_number = COALESCE(users.matriculation_number, EXCLUDED.matriculation_number),
                                          gender               = COALESCE(users.gender, EXCLUDED.gender),
                                          nationality          = COALESCE(users.nationality, EXCLUDED.nationality),
                                          cv_filename          = COALESCE(users.cv_filename, EXCLUDED.cv_filename),
                                          degree_filename      = COALESCE(users.degree_filename, EXCLUDED.degree_filename),
                                          examination_filename = COALESCE(users.examination_filename, EXCLUDED.examination_filename),
                                          study_degree         = COALESCE(users.study_degree, EXCLUDED.study_degree),
                                          study_program        = COALESCE(users.study_program, EXCLUDED.study_program),
                                          projects             = COALESCE(users.projects, EXCLUDED.projects),
                                          interests            = COALESCE(users.interests, EXCLUDED.interests),
                                          special_skills       = COALESCE(users.special_skills, EXCLUDED.special_skills),
                                          enrolled_at          = COALESCE(users.enrolled_at, EXCLUDED.enrolled_at),
                                          avatar               = COALESCE(users.avatar, EXCLUDED.avatar),
                                          research_group_id    = COALESCE(users.research_group_id, EXCLUDED.research_group_id);