-- ============================================================================
-- Manual insert script to add example users to the database for testing purposes.
--
-- This script:
--   - Inserts six example users with varying study programs, genders, and nationalities,
--   - Uses mixed realistic data for interests, projects, and skills,
--   - Demonstrates nullable fields like matriculation_number and research_group_id.
--
-- IMPORTANT:
-- This script is NOT part of the standard Liquibase migration process,
-- and must only be used for local development or manual test environments.
--
-- Author: Marc Fett
-- Date: 2025/05/06
-- ============================================================================

insert into users (user_id,
                   university_id,
                   matriculation_number,
                   email,
                   first_name,
                   last_name,
                   gender,
                   nationality,
                   cv_filename,
                   degree_filename,
                   examination_filename,
                   study_degree,
                   study_program,
                   projects,
                   interests,
                   special_skills,
                   enrolled_at,
                   updated_at,
                   joined_at,
                   custom_data,
                   avatar,
                   research_group_id)
values (gen_random_uuid(),
        'gb12abc',
        06000001,
        'sam_fischer@gmail.com',
        'Sam',
        'Fischer',
        'MALE',
        'DE',
        NULL,
        NULL,
        NULL,
        'MASTER',
        'COMPUTER_SCIENCE',
        'AI-based tutor recommendation system',
        'Educational technology, backend development',
        'Java, Spring Boot, PostgreSQL',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'gb34def',
        06000002,
        'jane_doe@gmail.com',
        'Jane',
        'Doe',
        'FEMALE',
        'US',
        NULL,
        NULL,
        NULL,
        'BACHELOR',
        'INFORMATION_SYSTEMS',
        NULL,
        'Process optimization, business analytics',
        NULL,
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'gb56ghi',
        06000003,
        'joey_read@gmail.com',
        'Joey',
        'Read',
        'OTHER',
        'CA',
        NULL,
        NULL,
        NULL,
        'MASTER',
        'GAMES_ENGINEERING',
        'Streaming pipeline for sensor data',
        'Real-time systems, cloud platforms',
        'Python, Kafka, AWS',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'gb78jkl',
        NULL,
        'barney_young@gmail.com',
        'Barney',
        'Young',
        'MALE',
        'DE',
        NULL,
        NULL,
        NULL,
        'BACHELOR',
        'MANAGEMENT_AND_TECHNOLOGY',
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'gb90mno',
        06000005,
        'chloe_mitchell@gmail.com',
        'Chloe',
        'Mitchell',
        'FEMALE',
        'FR',
        NULL,
        NULL,
        NULL,
        'MASTER',
        'OTHER',
        'Usability study for academic tools',
        'Interface design, eye-tracking',
        'Figma, UX research',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL),
       (gen_random_uuid(),
        'gb23pqr',
        NULL,
        'kelly_wilkins@gmail.com',
        'Kelly',
        'Wilkins',
        'FEMALE',
        'UK',
        NULL,
        NULL,
        NULL,
        'BACHELOR',
        'OTHER',
        NULL,
        'Web design, media production',
        'Adobe Suite, HTML/CSS',
        NOW(),
        NOW(),
        NOW(),
        NULL,
        NULL,
        NULL);