name: Run Tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Set up Java for server tests
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./server/gradlew

      # Run tests for server
      - name: Run server tests
        working-directory: ./server
        run: |
          ./gradlew test